vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        image_manga_serie:
            uri_prefix: /images/manga/serie
            upload_destination: '%kernel.project_dir%/public/images/manga/serie'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
